---
- hosts: all
  become: true
  vars:
    config_path: /opt/server-apps
    compose_file_path: "{{config_path}}/compose.yml"

  tasks:
    - name: Set up the Docker repository
      shell: |
        apt-get update
        apt-get install -y ca-certificates curl gnupg lsb-release
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        chmod a+r /etc/apt/keyrings/docker.gpg
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Check docker & compose versions
      shell: |
        docker --version
        docker compose version
    - name: Create project folder
      file:
        path: "{{config_path}}"
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Services down
      shell: |
        docker compose -f {{compose_file_path}} down
    - name: Copy/update config file with owner and permissions
      copy:
        src: "compose.yml"
        dest: "{{compose_file_path}}"
    - name: Serivces up
      shell: |
        docker compose -f {{compose_file_path}} up -d --pull always --quiet-pull
