baseURL = "https://dmmeteo.dev/"
languageCode = 'en-us'
theme = "coming-soon"
publishDir = "../docs"

[params]
    title = "The new dmmeteo.dev"
    description = "A portfolio and blog site"
    message = "COMING SOON!"
    release = "June 30, 2024"

socialIcons = [
    {name = "email", url = "dmmeteo@gmail.com"},
    {name = "twitter", url = "https://twitter.com/dmmeteo"},
    {name = "github", url = "https://github.com/dmmeteo"},
]

[params.twitter]
	enable = true
	username = "dmmeteo"
