version: "3.9"

services:
  wireguard:
    image: weejewel/wg-easy:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # Change the server's hostname (clients will connect to):
      - WG_HOST=${WGUI_HOST}
      # Change the Web UI Password:
      - PASSWORD=${WGUI_PASSWORD}
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      # UDP Routers
      - "traefik.udp.routers.wireguard-udp.entrypoints=streaming"
      # UDP Services
      - "traefik.udp.routers.wireguard-udp.service=wireguard-udp-svc"
      - "traefik.udp.services.wireguard-udp-svc.loadbalancer.server.port=51820"
      # HTTP Routers
      - "traefik.http.routers.wireguard-ui.entrypoints=web,websecure"
      - "traefik.http.routers.wireguard-ui.rule=Host(`${WGUI_HOST}`)"
      # HTTP Services
      - "traefik.http.routers.wireguard-ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.wireguard-ui-svc.loadbalancer.server.port=51821"
    volumes:
      - ./wireguard:/etc/wireguard

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    restart: unless-stopped
    environment:
      - AUTHENTICATE_VIA_JUPYTER=${JUPYTER_PASSWORD}
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.jupyter.entrypoints=websecure"
      - "traefik.http.routers.jupyter.rule=Host(`${JUPYTER_HOST}`)"
      # HTTP Services
      - "traefik.http.routers.jupyter.tls=true"
      - "traefik.http.routers.jupyter.tls.certresolver=letsencrypt"
      - "traefik.http.services.jupyter-svc.loadbalancer.server.port=8888"
      - "traefik.http.services.jupyter-svc.loadbalancer.server.scheme=https"
    volumes:
      - ./jupyter/config:/home/jovyan/.jupyter
      - ./jupyter/workspace:/home/jovyan/work
    ports:
      - 8888:8888

  traefik:
    image: traefik:v2.9.6
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      # HTTP & UDP Routers
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.streaming.address=:51820/udp"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # SSL Certificates
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCTYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Kasm (insecure connection between Traefik and the backend servers)
      - "--serverstransport.insecureskipverify"
      - "--log=true"
      - "--log.level=DEBUG"
    network_mode: host
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - production