version: "3.9"
# TODO: you can run all this stuff in a swarm mode
# OR create kube cluster with kind and deploy all this stuff there

services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # Change the server's hostname (clients will connect to):
      - WG_HOST=${WGUI_HOST}
      # Change the Web UI Password:
      - PASSWORD=${WGUI_PASSWORD}
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      # UDP Routers
      - "traefik.udp.routers.wireguard-udp.entrypoints=streaming"
      # UDP Services
      - "traefik.udp.routers.wireguard-udp.service=wireguard-udp-svc"
      - "traefik.udp.services.wireguard-udp-svc.loadbalancer.server.port=51820"
      # HTTP Routers
      - "traefik.http.routers.wireguard-ui.entrypoints=web,websecure"
      - "traefik.http.routers.wireguard-ui.rule=Host(`${WGUI_HOST}`)"
      # HTTP Services
      - "traefik.http.routers.wireguard-ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.wireguard-ui-svc.loadbalancer.server.port=51821"
    volumes:
      - /opt/server-apps/wireguard:/etc/wireguard

  shlink:
    image: shlinkio/shlink:latest
    container_name: shlink
    restart: unless-stopped
    environment:
      - DEFAULT_DOMAIN=${SHLINK_BE_HOST}
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=${SHLINK_LICENSE_KEY}
      # command to generate API key: docker compose exec shlink shlink api-key:generate
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.shlink.entrypoints=web,websecure"
      - "traefik.http.routers.shlink.rule=Host(`${SHLINK_BE_HOST}`)"
      # HTTP Services
      - "traefik.http.routers.shlink.tls=true"
      - "traefik.http.routers.shlink.tls.certresolver=letsencrypt"
      - "traefik.http.services.shlink-svc.loadbalancer.server.port=8080"
    volumes:
      - /opt/server-apps/shlink/data:/etc/shlink/data

  shlink-ui:
    image: dmmeteo/shlink-web-client:latest
    container_name: shlink-ui
    restart: unless-stopped
    environment:
      - SHLINK_API_URL=https://${SHLINK_HOST}
      - SHLINK_BASIC_AUTH_USERS=${SHLINK_BASIC_AUTH_USERS}
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.shlink-ui.entrypoints=web,websecure"
      - "traefik.http.routers.shlink-ui.rule=Host(`${SHLINK_FE_HOST}`)"
      # HTTP Services
      - "traefik.http.routers.shlink-ui.tls=true"
      - "traefik.http.routers.shlink-ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.shlink-ui-svc.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.10.5
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      # Logging
      - "--log=true"
      - "--log.level=DEBUG"
      # HTTP & UDP Routers
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.streaming.address=:51820/udp"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # SSL Certificates
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCTYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    network_mode: host
    volumes:
      - /opt/server-apps/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - production