name: Deploy Apps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-apps:
    runs-on: ubuntu-latest
    env:
      # Build level envs
      TEMP_FILES: .github/files
      WGUI_HOST: ${{ vars.WGUI_HOST }}
      WGUI_PASSWORD: ${{ secrets.WGUI_PASSWORD }}
      JUPYTER_HOST: ${{ vars.JUPYTER_HOST }}
      JUPYTER_PASSWORD: ${{ secrets.JUPYTER_PASSWORD }}
      PIHOLE_HOST: ${{ vars.PIHOLE_HOST }}
      PIHOLE_PASSWORD: ${{ secrets.PIHOLE_PASSWORD }}
      SHLINK_HOST: ${{ vars.SHLINK_HOST }}
      SHLINK_LICENSE_KEY: ${{ secrets.SHLINK_LICENSE_KEY }}
      LETSENCTYPT_EMAIL: ${{ vars.LETSENCTYPT_EMAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create temp files folder
        run: mkdir ${{ env.TEMP_FILES }}
      - name: Check docker & compose versions
        run: |
          docker --version
          docker compose version
      - name: Create docker compose config file
        run: |
          docker compose \
            --profile production \
            --file server-apps/compose.yml \
            convert > ${{ env.TEMP_FILES }}/compose.yml
      - name: Check docker compose config file
        run: |
          docker compose \
            --profile production \
            --file ${{ env.TEMP_FILES }}/compose.yml \
            config
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible-deploy.yml
          directory: .github/
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ vars.ANSIBLE_INVENTORY_HOST }}
          options: |
            --user root
            --verbose